# Generated by Django 2.1.3 on 2018-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_checkout', models.BooleanField()),
                ('payment_complete', models.BooleanField()),
                ('payment_txn', models.IntegerField()),
            ],
        ),
    ]
