# Generated by Django 2.1.3 on 2018-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20181106_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='payment_txn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
