# Generated by Django 2.1.3 on 2018-11-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20181106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidding.Bidder'),
        ),
    ]
