# Generated by Django 2.1.3 on 2018-11-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20181106_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
    ]
