# Generated by Django 2.1.3 on 2018-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20181106_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
